# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdEditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='cdEditor',
        ),
    ]
