# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdEditor', '0002_auto_20190307_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='editor',
            new_name='program',
        ),
    ]
