# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdEditor', '0003_auto_20190307_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
    ]
