# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdEditor', '0004_remove_program_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
