# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdEditor', '0008_auto_20190312_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='output',
            field=models.TextField(blank='true'),
        ),
    ]
