# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdEditor', '0009_auto_20190312_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='commandLineArgs',
            field=models.TextField(blank='true'),
        ),
    ]
