# Generated by Django 2.1.7 on 2019-04-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdEditor', '0010_auto_20190312_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
